sudo: required
dist: trusty

# Required as per https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2
group: edge

language: python
python:
    - "2.7"
install:
    - pip install .
    - pip install -r requirements.txt
    - sudo apt install python-tk
script: pytest
